replicaCount: 1

image:
  repository: 452676057290.dkr.ecr.eu-central-1.amazonaws.com/bogdanpashtet/godiploma
  pullPolicy: IfNotPresent
  tag: ""

appConfig: |
  grpc:
    port: 13013
  appName: "godiploma"
  version: "v0.3.18"
  httpHealth:
    port: 8080
    readyEndpoint: "/readyz"
    liveEndpoint: "/livez"
  metrics:
    port: 8081
    endpoint: "/metrics"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452676057290:role/GODIPLOMA-APP-ECR-PULL-ROLE

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 13013

containerPort: 13013
httpHealthPort: 8080
metricsPort: 8081

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
     cpu: 20m
     memory: 128Mi
   requests:
     cpu: 10m
     memory: 16Mi

livenessProbe:
  httpGet:
    path: /livez
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
