apiVersion: v1
kind: Service
metadata:
  name: {{ include "godiploma.fullname" . }}
  labels:
    {{- include "godiploma.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "godiploma.selectorLabels" . | nindent 4 }}
