[tool.bumpversion]
    current_version = "0.3.3"
    commit = true
    tag = true
    message = "Bump version {current_version} → {new_version}"
    tag_name = "v{new_version}"

    parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'
    serialize = ["{major}.{minor}.{patch}"]

[file."config/config.yaml"]
    search = 'version: "v{current_version}"'
    replace = 'version: "v{new_version}"'

#[file."deployments/helm/Chart.yaml"]
#    search = 'appVersion: "{current_version}"'
#    replace = 'appVersion: "{new_version}"'
#
#[file."deployments/helm/values.yaml"]
#    search = 'version: "v{current_version}"'
#    replace = 'version: "v{new_version}"'
#
#[file."README.md"]
#    search = 'version: v{current_version}'
#    replace = 'version: v{new_version}'
#
#[file."Taskfile.yml"]
#    search = 'APP_VERSION: v{current_version}'
#    replace = 'APP_VERSION: v{new_version}}'