[tool.bumpversion]
    current_version = "0.3.32"
    commit = true
    tag = true
    message = "Bump version {current_version} → {new_version}"
    tag_name = "v{new_version}"
    parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'
    serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
    filename = "config/config.yaml"
    search = 'version: "v{current_version}"'
    replace = 'version: "v{new_version}"'

[[tool.bumpversion.files]]
    filename = "deployments/helm/godiploma/Chart.yaml"
    search = 'appVersion: "{current_version}"'
    replace = 'appVersion: "{new_version}"'

[[tool.bumpversion.files]]
    filename = "README.md"
    search = 'version: v{current_version}'
    replace = 'version: v{new_version}'

[[tool.bumpversion.files]]
    filename = "Taskfile.yml"
    search = 'APP_VERSION: v{current_version}'
    replace = 'APP_VERSION: v{new_version}'

[[tool.bumpversion.files]]
    filename = "deployments/helm/godiploma/values.yaml"
    search = 'version: "v{current_version}"'
    replace = 'version: "v{new_version}"'

[[tool.bumpversion.files]]
    filename = "deployments/helm/godiploma/values.local.yaml"
    search = 'tag: "v{current_version}"'
    replace = 'tag: "v{new_version}"'