{
 "title": "K6",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data source",
    "query": "victoriametrics-metrics-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "k6_checks_rate", "legendFormat": "{{check}}" }
   ]
  },
  {
   "title": "Virtual Users (VUs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=\"k6_vus\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Received per Second (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(k6_data_received_total{scenario=\"default\"}[1m])",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Data Sent per Second (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(k6_data_sent_total{scenario=\"default\"}[1m])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Iteration Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "k6_iteration_duration_p99{}", "legendFormat": "{{scenario}}" }
   ]
  },
  {
   "title": "gRPC Request Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "k6_grpc_req_duration_p99{}", "legendFormat": "{{method}} - {{status}}" }
   ]
  },
  {
   "title": "Iterations per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "{__name__=\"k6_iterations_total\"}"
    }
   ]
  }
 ]
}